[project]
name = "dynamic_routing_analysis"
version = "0.1.0"
description = "Tools for accessing, processing and presenting data from Dynamic Routing experiments."
authors = [
    {name = "Ben Hardcastle", email = "ben.hardcastle@alleninstitute.org"},
    {name = "Ethan McBride", email = "ethan.mcbride@alleninstitute.org"},
]
dependencies = [
    "numpy>=1.24.4",
    "pandas>=2.0.3",
    "matplotlib>=3.7.2",
    "pynwb>=2.3.3",
    "nwbwidgets>=0.11.3",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
dev = [
    "mypy>=1.4.1",
    "pytest>=7.4.0",
    "ruff>=0.0.279",
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
